{% set version = "2.2.0" %}

package:
  name: scikit-ued
  version: {{ version }}

source:
  fn: scikit-ued-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/s/scikit-ued/scikit_ued-{{ version }}.tar.gz
  sha256: 902998e5dac3c039d956c5aa9366cdac5558390af2765415167f3be4e0756170

build:
  noarch: python
  number: 1
  entry_points:
    - skued = skued.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy >=1.17, <3
    # See https://github.com/scipy/scipy/issues/17740
    - scipy >=1.5.0, <2, !=1.10.0
    - scikit-image >=0.19, <1
    - pywavelets >=1.0.0, <2
    - crystals >=1.3.1, <2
    - npstreams >=1.6.5, <2
    - pyyaml >=3.1
    - matplotlib-base >=3.5, <4

test:
  requires:
    - pytest >= 6
    - python {{ python_min }}
  imports:
    - skued
  commands:
    - skued --help
    - pytest --pyargs skued

about:
  home: https://github.com/LaurentRDC/scikit-ued
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Collection of algorithms and functions for ultrafast electron diffraction
  description: Collection of algorithms and functions for ultrafast electron diffraction.
  doc_url: https://scikit-ued.readthedocs.io/
  dev_url: https://github.com/LaurentRDC/scikit-ued

extra:
  recipe-maintainers:
    - LaurentRDC
