{% set version = "2.0.4" %}

package:
  name: scikit-ued
  version: {{ version }}

source:
  fn: scikit-ued-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scikit-ued/scikit-ued-{{ version }}.tar.gz
  sha256: 937d94076f93a772dd75969e8289d4b7a9602dba8fdb1844831708dc2ab61b1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.15, <2
    - scipy >=1.0.0, <2
    - scikit-image >=0.15, <0.19
    - tifffile >=0.13, <1
    - pywavelets >=1.0.0, <2
    - crystals >=1.1.2, <2
    - npstreams >=1.6.2, <2
    - pyyaml >=3.1, <4
    - matplotlib-base >=3.0.0, <4

test:
  imports:
    - skued

about:
  home: https://github.com/LaurentRDC/scikit-ued
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Collection of algorithms and functions for ultrafast electron diffraction
  description: Collection of algorithms and functions for ultrafast electron diffraction.
  doc_url: https://scikit-ued.readthedocs.io/
  dev_url: https://github.com/LaurentRDC/scikit-ued

extra:
  recipe-maintainers:
    - LaurentRDC
